### ISSUE TITLE
How is this related

### ISSUE THREAD

**Issue by yatabani** [morlandi/django-datatables-view#12]
Is this repository related to https://pypi.org/project/django-datatables-view/

Which one is based-up on which

**Comment by morlandi** [comment]
Hello @yatabani 
https://pypi.org/project/django-datatables-view/ is based on Django class-based views, and has a completely different approach.
The two projects are totally unrelated, they just happen to share the same project name.

When I started this project for my own needs, I did some research, and finally ended up choosing this as a starting point for experiments: https://github.com/monnierj/django-datatables-server-side. Since then, I moved far away from the initial solution, however: I don't think my project has much in common with it now.

I regret that I choose a name already in use on PyPI; that that was a silly mistake on my side.
Sooner or later, I'll find the time to rename my project and publish it on PyPI ... till then, I'm just installing it from github

**Comment by yatabani** [comment]
Thanks for your response, it took me sometime to realize they are different. It is abit confusing.

Good luck
