### ISSUE TITLE
table_row_id_fieldname does not work as expect with details

### ISSUE THREAD

**Issue by tboulogne** [morlandi/django-datatables-view#13]
Hello,

Hope everything well.
Just give a try to the last version (3.2.3). I got a table with a pk field id named "rel_id" (Not id).

I setup the 
```
table_row_id_fieldname = 'red_id'
```

And i got this message when i click on the plus

```
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. 
Choices are: red_available, red_comp, red_compname, red_description, red_id,
```

Misunderstanding from my side ?

Thanks for help.

Regards

**Comment by morlandi** [comment]
Hello @tboulogne, nice to hear of you.
We're all well and good, thanks; hope the same for you.
Thank you for reporting this issue.
I'll check it and be back to this in a few days

table_row_id_fieldname is just used to add an id attribute to the HTML table; the error could very well be related to other parts of the code. Did you get a stacktrace ?

**Comment by tboulogne** [comment]
Hello @morlandi 

Nice here too.

Do you remember our discussion about custom_id ? The error is related to the id name field for requesting details information :-).

You consider the ID name field is always "id"
```
    def render_row_details(self, id, request=None):

        obj = self.model.objects.get(id=id)
```

So for custom ID name fields  (i always prefix my id field name), for example, this request should be for me :
```
def render_row_details(self, id, request=None):

        obj = self.model.objects.get(my_prefixed_id=id)
```

Do you understand my meaning ?
If i remember, you was talking about this table **table_row_id_fieldname** to solve this.

**Comment by morlandi** [comment]
> obj = self.model.objects.get(my_prefixed_id=id)

Correct. 
However, the "Django way" to do this is:
```
    def render_row_details(self, pk, request=None):
        obj = self.model.objects.get(pk=pk)
```

**Comment by morlandi** [comment]
@tboulogne since I'm using the package in a real project these days, I was finally able to work at least on the "custom_id" issue.

I opted for a more "Django-like" approach, accepting "pk" instead of "id" .. and also did some cleanup to the JS.

Since in the meantime the project has been renamed to “django-ajax-datatable” to avoid a conflict on PyPI, you will find the fix here:

https://github.com/morlandi/django-ajax-datatable/commit/482ee1da1c04bdb04fabff567ef33d1fde7e06c1

You can either backport this commit into your fork, or eventually migrate you project to use the renamed app; this requires very few changes, summarized here:

https://github.com/morlandi/django-ajax-datatable/blob/master/MIGRATE_FROM_DATATABLES_VIEW_CHECKLIST.rst

and finally add “django-ajax-datatable” to your project’s requirements, so it will be downloaded directly from PyPI
