### ISSUE TITLE
internationalization and filtres

### ISSUE THREAD

**Issue by tboulogne** [morlandi/django-datatables-view#9]
Hello,

If i enabled internationalization :
```
 language: {
   'url': '//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json'
  },
```

it works, but i lost columns filters:
Without internat:
![image](https://user-images.githubusercontent.com/6205275/75081766-bf90d880-5510-11ea-9214-0f41d0226b5a.png)

With internat:
![image](https://user-images.githubusercontent.com/6205275/75081788-d3d4d580-5510-11ea-942a-77c7f33a147a.png)

Any idea :-) please ?

Thanks for help :-)

**Comment by morlandi** [comment]
Hello @tboulogne 
since the "filter machinery" in injected via javascript, a possible explanation for that would be some javascript error occurring in your template. Can you detect any javascript error with the inspector of your browser ?

I do localize Datatable messages sometimes, and never noticed any problem with filters.

I just added an example in the Readme of the project:

https://github.com/morlandi/django-datatables-view#internationalization

Hope it helps,
ciao 
Mario

P.S. please note that last week I changed the filters quite a bit, in order to accomodate the optional use of "select" instead of "input", and a "Excel-like autofilter" funtionality. 
It's still very new code, and might need some adjustments here and there ... be aware of this ;)

**Comment by tboulogne** [comment]
Hello @morlandi 

If i push translation string in language and not using url, it works. So for now,  no worry :-)
